name: Build

on:
    create:
        tag:
            - "v*"
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Test
              uses: ianwalter/pnpm-container@v1.1.0
              run: |
                  pnpm i
                  pnpm run -r test:all
                  pnpm run -r build:all
                  pnpm run -r lint:all
